apiVersion: batch/v1
kind: Job
metadata:
  name: job-listing-data-manager-config-restore
  namespace: job-listing
spec:
  backoffLimit: 2
  template:
    spec:
      containers:
        - name: restore
          image: ghcr.io/coreymerritt/rsync:1.0.0
          env:
            - name: TZ
              value: "America/New_York"
          volumeMounts:
            - name: source
              mountPath: /source
              readOnly: true
            - name: destination
              mountPath: /destination
            - name: backup
              mountPath: /backup
      imagePullSecrets:
        - name: ghcr
      restartPolicy: OnFailure
      volumes:
        - name: source
          nfs:
            server: nfs-server.lan
            path: /misc/prod-data/backups/job-listing-data-manager/config
        - name: destination
          persistentVolumeClaim:
            claimName: job-listing-data-manager-config
        - name: backup
          nfs:
            server: nfs-server.lan
            path: /misc/prod-data/backups/job-listing-data-manager/config.deleted-during-restore
