apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-library
spec:
  capacity:
    storage: 8Ti   # Symbolic for NFS -- not enforced -- just informational
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain   # Never let k8s delete real media on PVC teardown
  nfs:
    server: nfs-server.lan
    path: /media
