apiVersion: apps/v1
kind: Deployment
metadata:
  name: tm-downloader
  namespace: tm
  labels:
    app: tm-downloader
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: tm-downloader
  template:
    metadata:
      labels:
        app: tm-downloader
    spec:
      imagePullSecrets:
        - name: ghcr
      containers:
        - name: tm-downloader
          image: ghcr.io/coreymerritt/tm.downloader:f53be8f7-75fc-4b1d-94a8-8ebdc4ed0990
          envFrom:
            - configMapRef:
                name: tm-downloader
            - configMapRef:
                name: tm-global
            - secretRef:
                name: tm-global
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Gi
          volumeMounts:
            - name: tm-files
              mountPath: /mnt/misc/prod-data/live/tm
      volumes:
        - name: tm-files
          nfs:
            server: nfs-server.lan
            path: /misc/prod-data/live/tm
