apiVersion: apps/v1
kind: Deployment
metadata:
  name: tm-converter
  namespace: tm
  labels:
    app: tm-converter
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: tm-converter
  template:
    metadata:
      labels:
        app: tm-converter
    spec:
      imagePullSecrets:
        - name: ghcr
      containers:
        - name: tm-converter
          image: ghcr.io/coreymerritt/tm.converter:2e55dbce-734e-4f12-b4fe-2d94e677b462
          envFrom:
            - configMapRef:
                name: tm-converter
            - configMapRef:
                name: tm-global
            - secretRef:
                name: tm-global
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - name: tm-files
              mountPath: /mnt/misc/prod-data/live/tm
      volumes:
        - name: tm-files
          nfs:
            server: nfs-server.lan
            path: /misc/prod-data/live/tm
