apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: job-listing-data-manager-config
  namespace: job-listing
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
