apiVersion: v1
kind: ConfigMap
metadata:
  name: sc2-data-manager
  namespace: sc2
data:
  SC2_DATA_MANAGER_CPU_CHECK_INTERVAL_SECONDS: "1.0"
  SC2_DATA_MANAGER_CPU_MAXIMUM_HEALTHY_USAGE_PERCENTAGE: "90.0"
  SC2_DATA_MANAGER_DISK_MAXIMUM_HEALTHY_USAGE_PERCENTAGE: "90.0"
  SC2_DATA_MANAGER_EXTERNAL_SERVICES_REQUEST_TIMEOUT: "15.0"
  SC2_DATA_MANAGER_GAME_SUMMARY_FILES_DIRECTORY: "/sc2-data-manager"
  SC2_DATA_MANAGER_GLOBAL_CONFIG_DIR: "/etc/sc2_data_manager"
  SC2_DATA_MANAGER_LOGGER_JSON: "false"
  SC2_DATA_MANAGER_LOGGER_LEVEL: "debug"
  SC2_DATA_MANAGER_LOGGER_TIMEZONE: "UTC"
  SC2_DATA_MANAGER_MEMORY_MAXIMUM_HEALTHY_USAGE_PERCENTAGE: "90.0"
  SC2_DATA_MANAGER_MODEL_CONFIG_DIR: "./config/models"
  SC2_DATA_MANAGER_PROJECT_NAME: "sc2_data_manager"
  SC2_DATA_MANAGER_TOKEN_ISSUER_TIME_TO_LIVE_DAYS: "365"
  SC2_DATA_MANAGER_UVICORN_ACCESS_LOG: "false"
  SC2_DATA_MANAGER_UVICORN_APP: "composition.webserver.hook:create_app"
  SC2_DATA_MANAGER_UVICORN_FACTORY: "true"
  SC2_DATA_MANAGER_UVICORN_HOST: "0.0.0.0"
  SC2_DATA_MANAGER_UVICORN_LOG_CONFIG: ".uvicorn.json"
  SC2_DATA_MANAGER_UVICORN_PORT: "23231"
  SC2_DATA_MANAGER_UVICORN_RELOAD: "true"
  SC2_DATA_MANAGER_UVICORN_SERVER_HEADER: "false"
  PYTHONPATH: "src"
