apiVersion: batch/v1
kind: Job
metadata:
  name: sc2-data-manager-db-restore
  namespace: sc2
spec:
  backoffLimit: 2
  template:
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - sc2-data-manager
              topologyKey: kubernetes.io/hostname
      containers:
        - name: restore
          image: ghcr.io/coreymerritt/rsync:1.0.0
          env:
            - name: TZ
              value: "America/New_York"
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
            - name: source
              mountPath: /source
              readOnly: true
            - name: destination
              mountPath: /destination
            - name: backup
              mountPath: /backup
      imagePullSecrets:
        - name: ghcr
      restartPolicy: OnFailure
      volumes:
        - name: source
          nfs:
            server: nfs-server.lan
            path: /misc/prod-data/backups/sc2-data-manager/db
        - name: destination
          persistentVolumeClaim:
            claimName: sc2-data-manager-db
        - name: backup
          nfs:
            server: nfs-server.lan
            path: /misc/prod-data/backups/sc2-data-manager/db.deleted-during-restore
