apiVersion: apps/v1
kind: Deployment
metadata:
  name: tm-download-producer
  namespace: tm
  labels:
    app: tm-download-producer
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: tm-download-producer
  template:
    metadata:
      labels:
        app: tm-download-producer
    spec:
      imagePullSecrets:
        - name: ghcr
      containers:
        - name: tm-download-producer
          image: ghcr.io/coreymerritt/tm.download-producer:1b6511db-23b1-471c-82d5-2d12b9787c34
          envFrom:
            - configMapRef:
                name: tm-download-producer
            - configMapRef:
                name: tm-global
            - secretRef:
                name: tm-global
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
