apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sc2-data-manager-config
  namespace: sc2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
