apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    name: observability
---
apiVersion: v1
kind: Namespace
metadata:
  name: job-listing
  labels:
    name: job-listing
---
apiVersion: v1
kind: Namespace
metadata:
  name: sc2
  labels:
    name: sc2
---
apiVersion: v1
kind: Namespace
metadata:
  name: jellyfin
  labels:
    name: jellyfin
