apiVersion: v1
kind: ConfigMap
metadata:
  name: tm-global
  namespace: tm
data:
  TM_GLOBAL_DATA_DIR: "/mnt/misc/prod-data/live/tm"
  TM_GLOBAL_DJANGO_ADDRESS: "tm-django"
  TM_GLOBAL_DJANGO_PORT: "8000"
  TM_GLOBAL_DJANGO_PROTOCOL: "http"
  TM_GLOBAL_RABBITMQ_ADDRESS: "rabbitmq-headless"
  TM_GLOBAL_RABBITMQ_PORT: "5672"
  TZ: "America/Detroit"
