apiVersion: apps/v1
kind: Deployment
metadata:
  name: trg
  namespace: trg
  labels:
    app: trg
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: trg
  template:
    metadata:
      labels:
        app: trg
    spec:
      imagePullSecrets:
        - name: ghcr
      containers:
        - name: trg
          image: ghcr.io/coreymerritt/trg:20013287-446f-495b-83c6-2051c5d3494e
          env:
            - name: TZ
              value: "America/New_York"
          envFrom:
            - configMapRef:
                name: trg
            - secretRef:
                name: secret-configs-trg
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
            - name: secret-configs-trg
              mountPath: /secret/configs
              readOnly: true
            - name: secret-ssh-trg
              mountPath: /root/.ssh
              readOnly: true
            - name: data
              mountPath: /data
      volumes:
        - name: secret-configs-trg
          secret:
            secretName: secret-configs-trg
        - name: secret-ssh-trg
          secret:
            secretName: secret-ssh-trg
            defaultMode: 0400
        - name: data
          nfs:
            server: nfs-server.lan
            path: /misc/prod-data/trg
