apiVersion: batch/v1
kind: Job
metadata:
  name: prometheus-data-restore
  namespace: observability
spec:
  backoffLimit: 2
  template:
    spec:
      containers:
        - name: restore
          image: ghcr.io/coreymerritt/rsync:1.0.0
          env:
            - name: TZ
              value: "America/New_York"
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
            - name: source
              mountPath: /source
              readOnly: true
            - name: destination
              mountPath: /destination
            - name: backup
              mountPath: /backup
      imagePullSecrets:
        - name: ghcr
      restartPolicy: OnFailure
      volumes:
        - name: source
          nfs:
            server: nfs-server.lan
            path: /misc/prod-data/backups/prometheus/data
        - name: destination
          persistentVolumeClaim:
            claimName: prometheus-data
        - name: backup
          nfs:
            server: nfs-server.lan
            path: /misc/prod-data/backups/prometheus/data.deleted-during-restore
