server {
    listen 80;
    server_name adguardhome.lan;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    http2 on;

    server_name adguardhome.lan;

    ssl_certificate /etc/nginx/certs/adguardhome.lan.pem;
    ssl_certificate_key /etc/nginx/certs/adguardhome.lan-key.pem;

    location / {
        proxy_pass http://adguardhome:13571;
        include /etc/nginx/snippets/proxy.conf;
    }
}
