server {
    listen 80;
    server_name job-listing-data-manager.lan;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    http2 on;

    server_name job-listing-data-manager.lan;

    ssl_certificate /etc/nginx/certs/job-listing-data-manager.lan.pem;
    ssl_certificate_key /etc/nginx/certs/job-listing-data-manager.lan-key.pem;

    location / {
        proxy_pass http://job-listing-data-manager:7937;
        include /etc/nginx/snippets/proxy.conf;
    }
}
